"""initial_schema

Revision ID: 17f0eca1a355
Revises: 
Create Date: 2026-03-27 21:59:31.306611
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f0eca1a355'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('numbers_pool', sa.Integer(), nullable=False),
    sa.Column('numbers_drawn', sa.Integer(), nullable=False),
    sa.Column('min_number', sa.Integer(), nullable=False),
    sa.Column('max_number', sa.Integer(), nullable=False),
    sa.Column('stars_pool', sa.Integer(), nullable=True),
    sa.Column('stars_drawn', sa.Integer(), nullable=True),
    sa.Column('star_name', sa.String(length=50), nullable=True),
    sa.Column('draw_frequency', sa.String(length=50), nullable=False),
    sa.Column('historical_source', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_definitions_slug'), 'game_definitions', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'UTILISATEUR', 'CONSULTATION', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=True),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('stars', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'draw_date', name='uq_draw_game_date')
    )
    op.create_index(op.f('ix_draws_draw_date'), 'draws', ['draw_date'], unique=False)
    op.create_index(op.f('ix_draws_game_id'), 'draws', ['game_id'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_executions_job_name'), 'job_executions', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_executions_started_at'), 'job_executions', ['started_at'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('grid_count', sa.Integer(), nullable=False),
    sa.Column('grids', sa.JSON(), nullable=False),
    sa.Column('diversity_score', sa.Float(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('avg_grid_score', sa.Float(), nullable=False),
    sa.Column('min_hamming_distance', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_game_id'), 'portfolios', ['game_id'], unique=False)
    op.create_table('scored_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('stars', sa.JSON(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('simulation_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scored_grids_game_id'), 'scored_grids', ['game_id'], unique=False)
    op.create_index(op.f('ix_scored_grids_is_top'), 'scored_grids', ['is_top'], unique=False)
    op.create_index(op.f('ix_scored_grids_rank'), 'scored_grids', ['rank'], unique=False)
    op.create_index(op.f('ix_scored_grids_total_score'), 'scored_grids', ['total_score'], unique=False)
    op.create_table('statistics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('draw_count', sa.Integer(), nullable=False),
    sa.Column('frequencies', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('cooccurrence_matrix', sa.JSON(), nullable=False),
    sa.Column('temporal_trends', sa.JSON(), nullable=False),
    sa.Column('bayesian_priors', sa.JSON(), nullable=False),
    sa.Column('graph_metrics', sa.JSON(), nullable=False),
    sa.Column('distribution_stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_snapshots_computed_at'), 'statistics_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_statistics_snapshots_game_id'), 'statistics_snapshots', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_snapshots_game_id'), table_name='statistics_snapshots')
    op.drop_index(op.f('ix_statistics_snapshots_computed_at'), table_name='statistics_snapshots')
    op.drop_table('statistics_snapshots')
    op.drop_index(op.f('ix_scored_grids_total_score'), table_name='scored_grids')
    op.drop_index(op.f('ix_scored_grids_rank'), table_name='scored_grids')
    op.drop_index(op.f('ix_scored_grids_is_top'), table_name='scored_grids')
    op.drop_index(op.f('ix_scored_grids_game_id'), table_name='scored_grids')
    op.drop_table('scored_grids')
    op.drop_index(op.f('ix_portfolios_game_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_job_executions_started_at'), table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_job_name'), table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index(op.f('ix_draws_game_id'), table_name='draws')
    op.drop_index(op.f('ix_draws_draw_date'), table_name='draws')
    op.drop_table('draws')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_game_definitions_slug'), table_name='game_definitions')
    op.drop_table('game_definitions')
    # ### end Alembic commands ###
