"""add_star_statistics_columns

Revision ID: 6773450d8c55
Revises: 17f0eca1a355
Create Date: 2026-03-28 19:45:03.461302
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6773450d8c55'
down_revision: Union[str, None] = '17f0eca1a355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics_snapshots', sa.Column('star_frequencies', sa.JSON(), nullable=True))
    op.add_column('statistics_snapshots', sa.Column('star_gaps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics_snapshots', 'star_gaps')
    op.drop_column('statistics_snapshots', 'star_frequencies')
    # ### end Alembic commands ###
